#!/usr/bin/env node
// Run the normalization sweep and write docs/normalization-sweep.md.
//   node scripts/normalization-sweep.mjs   (npm run sweep)
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { runSweep, renderCase, evaluateCase } from './lib/sweep.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const rows = runSweep();

const GROUPS = {
  space: 'Space: camera framing and view',
  body: 'Space: body size and proportions',
  time: 'Time: frame rate, slow motion, clip timing',
  pro: 'The pro recorded differently',
  robust: 'Robustness: things that can only be reduced, not removed',
  sensitive: 'Sensitivity: one real difference at a time',
};

function verdict(r) {
  const x = r.res;
  if (r.kind === 'sensitive') {
    const caught = r.expect.every((id) => x.byId[id].severity !== 'good');
    const allowed = new Set([...r.expect, ...(r.allow || [])]);
    const extra = x.notGood.filter((id) => !allowed.has(id));
    return caught && !extra.length ? '✅ caught' : caught ? '⚠️ caught + extras' : '❌ missed';
  }
  if (r.kind === 'limit') return '❌ limit';
  if (!x.notGood.length && x.swingScore >= 95) return '✅';
  if (x.notGood.length <= 1 && x.swingScore >= 90) return '⚠️';
  return '❌';
}

const fmt = (v, d = 0) => (Number.isFinite(v) ? v.toFixed(d) : '—');
let md = `# Normalization sweep

Generated by \`npm run sweep\` (scripts/normalization-sweep.mjs) on ${new Date().toISOString().slice(0, 10)}.

**Method.** The procedural 3D swing model renders *the same swing* as placeholder pro A under many recording conditions. Each recording then goes through the full user pipeline: automatic stance pick and pitcher side, canonicalization, alignment with the pro, phase transfer and all ${rows[0].res.items.length} feedback checks. It is compared against pro A as stored in the database. Because the swing is identical, a perfect normalization reports **every check as "matches"**, a swing score of 100 and phases at their true times. Columns:

- **Swing / Stance**: swing-match and stance-similarity scores (%).
- **Phase error**: the worst error over load, foot plant, contact, extension and finish, in real milliseconds, against ground truth.
- **Flags**: checks that wrongly said "minor" or "work on". For sensitivity rows, the checks that reacted.
- **Worst**: the largest deviation in units of that check's tolerance (≥ 1 means flagged).

The same conditions run as tests in \`tests/normalization.test.mjs\` on every push.

`;

for (const [g, title] of Object.entries(GROUPS)) {
  const list = rows.filter((r) => r.group === g);
  if (!list.length) continue;
  md += `## ${title}\n\n| Condition | Result | Swing | Stance | Phase error | Flags | Worst |\n| --- | --- | --: | --: | --: | --- | --: |\n`;
  for (const r of list) {
    const x = r.res;
    const flags = x.notGood.length ? x.notGood.map((id) => `\`${id}\``).join(' ') : '—';
    md += `| ${r.name}${x.slowmoSuggested > 1 ? ` *(app suggests ${x.slowmoSuggested}× slow motion)*` : ''} | ${verdict(r)} | ${fmt(x.swingScore)} | ${fmt(x.stanceSimilarity)} | ${fmt(x.maxPhaseErrMs)} ms | ${flags} | ${fmt(x.worst.ratio, 2)} |\n`;
  }
  md += '\n';
}

// Noise across seeds.
md += '## Keypoint jitter across random seeds\n\n| Jitter | Seeds | False flags (total) | Worst |\n| --- | --: | --: | --: |\n';
for (const noisePx of [2, 5]) {
  const seeds = [3, 8, 15, 21, 33, 47, 52, 61];
  let flags = 0;
  let worst = 0;
  for (const seed of seeds) {
    const r = evaluateCase(renderCase({ render: { noisePx, seed } }));
    flags += r.notGood.length;
    worst = Math.max(worst, r.worst.ratio);
  }
  md += `| ${noisePx} px at 720p | ${seeds.length} | ${flags} | ${worst.toFixed(2)} |\n`;
}

md += `
## What the sweep found and what changed

Found in the first run, fixed in the same change:

1. **Child proportions lowered the swing score (83%) for an identical swing.** Swing scoring compared raw poses, so different limb proportions read as different positions. Now every pro frame is rescaled per bone to the hitter's proportions measured at the stance (\`proportionScales\` / \`rescaleBones\`). Bone directions and their foreshortening are kept, so rotation still shows. The on-video ghost uses the same fitting, which also stops its shoulders and hips from keeping a fixed width while they rotate. Now 99%.
2. **A tilted camera caused false flags** (1 flag at 3°, 4 at 8°: weight shift, spine tilt, balance). Canonicalization now levels the image using the ground line through both feet at the stance (big toes, else ankles), averaged over ±150 ms and only for tilts of 1–12°. Now 0 flags up to at least 8°. The same leveling is ported to the Python tool, and parity is tested.
3. **Slow motion with the speed left at "real time" broke everything:** wrong stance pick, phases about 290 ms off, 14 false flags. Even slow real swings move the hands at 5+ torso-lengths/s at their fastest, while a 4× replay peaks below 3. The app now spots this and offers **"Treat as N× slow motion"** without re-analyzing, and the Python tool prints a warning with the right \`--speed\`. With the suggestion accepted, 4× and 8× clips come out perfect.
4. **Contact was detected 1–2 frames off under keypoint jitter,** and around contact the shoulders turn about 17° per frame, so contact checks false-flagged (10 flags over 8 seeds at 5 px). Contact is now the centroid of the hand-speed peak instead of the single fastest frame: 1 borderline flag over 8 seeds. This also fixed the 10°-off-axis camera case.
5. **Stance values came from a single frame.** The stance reference, the stance checks and stance matching now average ±60 ms of the (still) stance.

## Known limits

- **Camera far off perpendicular (25°)** changes the 2D picture in ways a single camera can't undo. Many checks drift. Keep the camera within about 10° of perpendicular to the pitch path, where results are unaffected.
- **Slow motion that nobody tells the app about** is wrong until the suggestion is accepted. 2× slow motion overlaps with genuinely slow swings, so only clear cases (about 3× and up) are flagged automatically.
- Joint angles and hip and shoulder turn are *apparent* values in the camera plane. They are consistent across recordings of the same view, which is what the comparison needs.
- These conditions are synthetic. Real pose-model behavior (occlusion, motion blur, a bat hiding the hands) is only approximated here by jitter, dropouts, label flicker and a systematic keypoint bias.
`;

const out = join(root, 'docs', 'normalization-sweep.md');
writeFileSync(out, md);
console.log(`wrote ${out}`);
